# Generated by Django 3.2.3 on 2021-06-12 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Similarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.TextField()),
                ('tgt', models.TextField()),
                ('similarity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SourceSimilarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TranslationMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('src_lang', models.TextField()),
                ('tgt_lang', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TargetSimilarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('similarity', models.IntegerField()),
                ('src', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='similarity.sourcesimilarity')),
            ],
        ),
        migrations.CreateModel(
            name='SegmentPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src_segment', models.TextField()),
                ('tgt_segment', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('src', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='similarity.translationmemory')),
            ],
        ),
    ]
